# Develop profile (don't communicate with services, only send information to console)
spring.config.activate.on-profile=develop
# Telegram_develop
tg.username=checkdev_develop_bot
tg.token=6922116952:AAFyGK2RkKjulLRcC5IgBMigcZIyv2X_BTI

# Настройки для Retry
resilience4j.retry.instances.authRetry.maxAttempts=3
resilience4j.retry.instances.authRetry.waitDuration=500ms

# Настройки для Circuit Breaker
resilience4j.circuitbreaker.instances.authCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.authCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authCircuitBreaker.waitDurationInOpenState=10000ms
resilience4j.circuitbreaker.instances.authCircuitBreaker.slidingWindowSize=100
resilience4j.circuitbreaker.instances.authCircuitBreaker.permittedNumberOfCallsInHalfOpenState=10
