package ru.checkdev.notification.service;

public enum NotificationKafkaEventType {
    ADD_SUBSCRIBE_CATEGORY,
    DELETE_SUBSCRIBE_CATEGORY,
    ADD_SUBSCRIBE_TOPIC,
    DELETE_SUBSCRIBE_TOPIC,
    INTERVIEW_TOPIC_NOTIFICATION,
    INTERVIEW_CREATED,
    INNER_MESSAGE,
    FEEDBACK_NOTIFICATION,
    PARTICIPATE_AUTHOR,
    CANCEL_INTERVIEW,
    PARTICIPANT_IS_DISMISSED,
    APPROVED_WISHER
}
